version: '2'
services:
  nginx:
    build: .
    container_name: "wee-nginx"
    ports:
      - "10080:80"
    networks:
      - wee-net
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d

networks:
  wee-net:
    driver: bridge
