FROM debian:jessie 
MAINTAINER kolyjjj@foxmail.com
ADD http://nginx.org/keys/nginx_signing.key /tmp/nginx_signing.key
RUN apt-key add /tmp/nginx_signing.key \
    && echo "deb http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list \
    && echo "deb-src http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list \
    && apt-get update \
    && rm -rf /var/lib/apt/lists/*


