version: '2'
services:
  nginx:
    build: .
    container_name: "wee-nginx"
    ports:
      - "10080:80"
    networks:
      wee-net:
        ipv4_address: 172.16.238.11
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d

networks:
  wee-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
